---
bag_path: "examples/lab2_rosbag" # Required. The path to the rosbag directory you want to convert
project_dir: "out" # The output directory of the converted data. Defaults to ./{rosbag-name}-supervisely
project_type: "point_cloud_episodes" # Required. The project type of the supervisely dataset. Can be one of ['images', 'point_cloud_episodes']
topic_pairs: # Required. The topic pairs of image type and tag type, **seperated by comma**
  - (/sensing/lidar/bf_lidar/points_raw,)
