---
bag_path: "examples/image_rosbag" # Required. The path to the rosbag directory you want to convert
project_dir: "out" # The output directory of the converted data. Defaults to ./{rosbag-name}-supervisely
project_type: "images" # Required. The project type of the supervisely dataset. Can be one of ['images', 'point_cloud_episodes']
topic_pairs: # Required. The topic pairs of image type and tag type, **seperated by comma**
  - (/out/compressed, /groundtruth_pose)
